language: php

php:
    - 7.2
    - 7.3
    - 7.4

env:
    - COMPOSER_PREFER=--prefer-lowest
    - COMPOSER_PREFER=--prefer-stable

before_script:
    - phpenv config-rm xdebug.ini
    - composer update --dev $COMPOSER_PREFER

script:
    - make test
